(DEFUN sl_lists (&rest l)
	(if(EQUAL L NIL)
		(return NIL)
		T
	)
		(setq elems '() )
		(DOTIMES (cont (LENGTH l))
			(setq elems (APPEND elems (LIST (LENGTH ( car l) ) ) ) )
			(setq l (cdr l))
		)
		(APPLY #'= elems)
)
	;(APPLY 'min l)
	;(print (car l))
	;(setq l (cdr l))
	;(print (car l))
	;(setq l (cdr l))
	;(print (car l))
	;(setq l (cdr l))