(defun listv1 ()
	(setq x1 '(COCHE MOTO TREN))
	(setq x2 '(EDUARDO PEDRO ANTONIO))
	(setq xl (COPY-LIST x1))
	(NCONC xl x2)
	(PRINC "Length")
	(PRINT (LENGTH xl))
	(setq xp (LIST 
				(NTH 2 x1) 
				(NTH 2 x2)
			)
	)
	(PRINT xp)
	(setq xK (LIST 
				(LIST (NTH 2 x1) ) 
				(LIST (NTH 2 x2) ) 
			) 
	)
	(PRINT xk)
	(setq xh (LIST 
				(LIST (NTH 2 x1) ) 
				(NTH 2 x2) 
			) 
	)
	(PRINT xh)
	(setq x3 (COPY-LIST x1))
	(NCONC x3 (REVERSE x2))
)
